### ISSUE TITLE
Instructions for setup?

### ISSUE THREAD

**Issue by jbranchaud** [jackc/pgmock#1]
Hi,

I saw a demo of this project recently and I am a big fan. I'd like to use it to view the messages/queries being passed to a Postgres server. Do you have instructions for how to get this setup for that use case?

❤️ 💙 💜 💚 💛

**Comment by jackc** [comment]
I have a test and example usage now -- I do get back to things eventually ;)

**Comment by StevenACoffman** [comment]
Hey, so for those who are using this for testing, I found this example to be very instructive:
https://github.com/supabase/cli/blob/5c57860808a2b9333c654093edb9037bcbbb74cb/internal/testing/pgtest/mock.go

**Comment by StevenACoffman** [comment]
https://github.com/egon12/pgsnap provides snapshot recording and Fake PostgreSQL proxy for unit testing
