### ISSUE TITLE
proxy cannot work, exit with unexpected EOF

### ISSUE THREAD

**Issue by thetruechar** [jackc/pgmock#7]
my local postgres serve on port 7432, and psql can connect to it:
```
 psql -h localhost -p 7432 -U postgres postgres
Password for user postgres: 
psql (13.3, server 12.6)
```

but use proxy:

```
 go run pgmockproxy/main.go --listen=localhost:15432 --remote=localhost:7432
```
and  psql -h localhost -p 15432 -U postgres postgres
result:
```
F {"Type":"SSLRequest","ProtocolVersion":0,"Parameters":null}
2021/07/02 23:21:29 unexpected EOF
Exiting.
```

can't figure out what's wrong here, please help, thanks.

**Comment by jackc** [comment]
pgmockproxy doesn't currently support SSL. Disable it when connecting:

```
PGSSLMODE=disable psql -h localhost -p 15432 -U postgres postgres
```

**Comment by thetruechar** [comment]
Thank you, I figured it out too.

**Comment by nilansaha** [comment]
> pgmockproxy doesn't currently support SSL. Disable it when connecting:
> 
> ```
> PGSSLMODE=disable psql -h localhost -p 15432 -U postgres postgres
> ```

Is there any plans to support it in the future? I was also wondering how to pass in username and password

**Comment by jackc** [comment]
@nilansaha I'm not opposed to the feature, but it's not something I have any immediate plans to work on.
